import './reset.scss'
import './navbar.scss'
import './tweet.scss'
import './left-nav.scss'
import './main.scss'
import './friend-nav.scss'
import 'bootstrap/dist/css/bootstrap.css'
import '@fortawesome/fontawesome-free/js/all';
import '@fortawesome/fontawesome-free/css/all.min.css';